export const dataA = ``

export const dataB = `Basile, Anthony
Chan, Aidan
Chee, Benjamin
Clark, Daniel
Deng, Dawson
Falcone, Nicholas
Faltas, Matthew
Freitas, Brianna
Ganny, Bode
Gao, Phillip
Gu, Andrew
Guo, Yunting
Gupta, Sanjana
Johnson, Kaelyn
Li, Jason
Li, Kevin
Liu, Jiayue
Liu, Justin
McLaughlin, Grace
Munshi, Jaiman
Ni, Jennifer
Otash, Victoria
Pei, Andy
Pophali, Anika
Puthenpurayil, Nancy
Romer, Nicholas
Shen, Eric
Su, Spencer
Turner, Ryan
Verma, Kushagra
Wang, Orion
Yang, Chloe
Yekelchik, Benjamin
Zhang, Vivian`

export const dataC = `Arias, Cindy
Barrera Roccatti, David
Chan, Aidan
Chee, Benjamin
Cheng, Lawrence
Deng, Dawson
Falcone, Nicholas
Faltas, Matthew
Gao, Phillip
Gu, Andrew
Guo, Yunting
Gupta, Sanjana
Inscore, Jenna
Johnson, Kaelyn
Kong, Sherice
Li, Jason
Li, Kevin
Liu, Jiayue
Liu, Justin
Munshi, Jaiman
Ni, Jennifer
Otash, Victoria
Pei, Andy
Pophali, Anika
Puthenpurayil, Nancy
Shen, Eric
Skiadas, Theodore
Su, Spencer
Turner, Ryan
Verma, Kushagra
Wang, Orion
Yang, Chloe
Yekelchik, Benjamin
Zhang, Vivian`

export const dataD = `Arias, Cindy
Barrera Roccatti, David
Basile, Anthony
Chan, Aidan
Chee, Benjamin
Cheng, Lawrence
Clark, Daniel
Deng, Dawson
Falcone, Nicholas
Faltas, Matthew
Freitas, Brianna
Ganny, Bode
Gao, Phillip
Gu, Andrew
Guo, Yunting
Gupta, Sanjana
Inscore, Jenna
Johnson, Kaelyn
Kong, Sherice
Li, Jason
Li, Kevin
Liu, Jiayue
Liu, Justin
McLaughlin, Grace
Munshi, Jaiman
Ni, Jennifer
Otash, Victoria
Pei, Andy
Pophali, Anika
Puthenpurayil, Nancy
Romer, Nicholas
Shen, Eric
Skiadas, Theodore
Su, Spencer
Turner, Ryan
Verma, Kushagra
Wang, Orion
Yang, Chloe
Yekelchik, Benjamin
Zhang, Vivian`