const data = `Arulraj, Oviya
Chan, Matthew
Grace, Connor
Griffith, Caroline
Gunn, Sydney
Gurram, Krishna
Hackett, Kayleigh
Hairston, Luke
Hamilton, David
Henderson, Kate
Hess, Edward
Hockstein, William
Hornblow, Aidan
Hou, Kenji
Hu, AnnaBelle
Huang, Angelina
Hull, Vincent
Imperial, Izzy
Inampudi, Srija
Inscore, Jenna
Ji, Jonathan
Jiang, Spencer
Joshi, Pranav
Kalra, Nandita
Kerrick, Kaylin
Khalil, Seif
Khattar, Rhea
Khurana, Krish
Knudsen, Anya
Kokenge, Reid
Kottaparambil, Mehreen
Kozlowski, Maggie
Kramer, Timothy
LaCapra, Jane
Lake, Wyatt
Lakshmipathi, Daamodaran
Lardiere, Elianna
Larner, Benjamin
LaRose, Julia
Laska, Sean
LaTourette, Joshua
Lettie, Lucas
Lipke-Barbee, Colin
Ma, Lawrence
Rocha, Dylan`